Clase5 tarea
CamposRC-dev/ClaseHTML pull request #4
Opened 2023-03-27 07:21 UTC by CamposRC-dev

Realizando tarea de flexbox, creando youtube.

2023-03-27 21:23 UTC, alepaez-dev requested changes
ando bien business woman en friega estos dias asi que dejo mas tarea @CamposRC-dev 
1. que no se vaya a la derecha por la cantidad de videos que hay. Para esto investiga `flex-wrap` o `flex-grow`
2. Hazlo responsivo
Acabas esto te dejo mas tarea.
Siguiente tema: desafio mini enmaquetado para que sepas hacer una pagina sin ayuda de nada externo y despues tailwind
<img width="1512" alt="Screen Shot 2023-03-27 at 15 14 28" src="https://user-images.githubusercontent.com/74441510/228068404-b25003c1-99b6-40f0-b0f0-7cec11630d20.png">

2023-03-27 21:23 UTC, alepaez-dev commented on CSS/Clase5-Tarea.css
> +    text-overflow: ellipsis;
nice

2023-03-27 21:23 UTC, alepaez-dev commented on CSS/Clase5-Tarea.css
> +    flex-direction: row;
necesitas el `flex-direction: row` ?

2023-03-27 21:23 UTC, alepaez-dev commented on CSS/Clase5-Tarea.css
> +    flex-direction: row;
misma pregunta

2023-03-27 21:23 UTC, alepaez-dev commented on CSS/Clase5-Tarea.css
> +    justify-content: flex-start;
necesitas el `justify-content: flex-start` ??

2023-03-27 21:23 UTC, alepaez-dev commented on Clase5-Tarea.html
> +            <div class="topic" id="select">Videojuegos</div>
No puedes repetirs id's. Si quieres otra clase se pone `class="topic select"`. Con espacios entre clases. El id es único

2023-03-27 21:23 UTC, alepaez-dev commented on Clase5-Tarea.html
> +                            <span>Canal Tauro</span>
Ni quien vea este canal

2023-04-14 23:26 UTC, CamposRC-dev commented
Se realizaron los cambios recomendados

2023-04-14 23:27 UTC, merged